"""First changes

Revision ID: ac354bf3a746
Revises: d884c23bb060
Create Date: 2023-02-21 10:13:16.555817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac354bf3a746'
down_revision = 'd884c23bb060'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('email', sa.Text(), nullable=False))
    op.add_column('admins', sa.Column('password', sa.Text(), nullable=False))
    op.add_column('answers', sa.Column('title', sa.Text(), nullable=False))
    op.add_column('answers', sa.Column('is_correct', sa.Boolean(), nullable=False))
    op.add_column('questions', sa.Column('title', sa.Text(), nullable=False))
    op.add_column('questions', sa.Column('theme_id', sa.BigInteger(), nullable=False))
    op.add_column('themes', sa.Column('title', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('themes', 'title')
    op.drop_column('questions', 'theme_id')
    op.drop_column('questions', 'title')
    op.drop_column('answers', 'is_correct')
    op.drop_column('answers', 'title')
    op.drop_column('admins', 'password')
    op.drop_column('admins', 'email')
    # ### end Alembic commands ###
